-- Indian Railways — AI Block Planning
-- PostgreSQL schema for assets, defects, maintenance_tasks,
-- corridor_windows, blocks, and block_tasks.
--
-- Apply:
--   psql -d block_planning -v ON_ERROR_STOP=1 -f sql/schema.sql
--
-- Safe to re-run: drops existing objects in FK order, then recreates them.

BEGIN;

DROP TRIGGER IF EXISTS trg_blocks_updated_at ON blocks;
DROP TRIGGER IF EXISTS trg_corridor_windows_updated_at ON corridor_windows;
DROP TRIGGER IF EXISTS trg_maintenance_tasks_updated_at ON maintenance_tasks;
DROP TRIGGER IF EXISTS trg_defects_updated_at ON defects;
DROP TRIGGER IF EXISTS trg_assets_updated_at ON assets;

DROP TABLE IF EXISTS block_tasks CASCADE;
DROP TABLE IF EXISTS blocks CASCADE;
DROP TABLE IF EXISTS corridor_windows CASCADE;
DROP TABLE IF EXISTS maintenance_tasks CASCADE;
DROP TABLE IF EXISTS defects CASCADE;
DROP TABLE IF EXISTS assets CASCADE;

DROP FUNCTION IF EXISTS set_updated_at();

CREATE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- 1. assets
-- Track, OHE, signalling, P&C, bridges on a section.
-- ---------------------------------------------------------------------------
CREATE TABLE assets (
    asset_id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_type              varchar(40)  NOT NULL,
    sub_type                varchar(60)  NOT NULL,
    division_code           varchar(16)  NOT NULL,
    section_code            varchar(32)  NOT NULL,
    corridor_id             varchar(40)  NOT NULL,
    km_start                numeric(8, 3) NOT NULL,
    km_end                  numeric(8, 3) NOT NULL,
    line_category           varchar(16)  NOT NULL,
    traffic_density_class   varchar(8)   NOT NULL,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_assets_km_range CHECK (km_end >= km_start),
    CONSTRAINT ck_assets_line_category CHECK (
        line_category IN ('A', 'B', 'C', 'D', 'E', 'DFC', 'suburban')
    ),
    CONSTRAINT ck_assets_traffic_density_class CHECK (
        traffic_density_class IN ('A', 'B', 'C', 'D', 'E')
    )
);

CREATE INDEX ix_assets_asset_type ON assets (asset_type);
CREATE INDEX ix_assets_division_code ON assets (division_code);
CREATE INDEX ix_assets_section_code ON assets (section_code);
CREATE INDEX ix_assets_corridor_id ON assets (corridor_id);
CREATE INDEX ix_assets_division_section ON assets (division_code, section_code);
CREATE INDEX ix_assets_corridor_km ON assets (corridor_id, km_start, km_end);
CREATE INDEX ix_assets_type_subtype ON assets (asset_type, sub_type);

CREATE TRIGGER trg_assets_updated_at
    BEFORE UPDATE ON assets
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 2. defects
-- Reported failures / irregularities against assets.
-- ---------------------------------------------------------------------------
CREATE TABLE defects (
    defect_id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id                    integer     NOT NULL,
    department                  varchar(32) NOT NULL,
    defect_type                 varchar(80) NOT NULL,
    defect_severity             varchar(24) NOT NULL,
    detected_date               date        NOT NULL,
    detected_by                 varchar(80) NOT NULL,
    status                      varchar(24) NOT NULL DEFAULT 'open',
    recommended_action          text        NOT NULL,
    estimated_work_duration_min integer     NOT NULL,
    max_allowed_delay_days      integer     NOT NULL,
    source_system                varchar(40) NOT NULL,
    source_defect_id            varchar(64) NOT NULL,
    created_at                  timestamptz NOT NULL DEFAULT now(),
    updated_at                  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_defects_asset
        FOREIGN KEY (asset_id)
        REFERENCES assets (asset_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_defects_source UNIQUE (source_system, source_defect_id),
    CONSTRAINT ck_defects_severity CHECK (
        defect_severity IN ('critical', 'major', 'minor', 'observational')
    ),
    CONSTRAINT ck_defects_status CHECK (
        status IN ('open', 'acknowledged', 'in_progress', 'deferred', 'closed')
    ),
    CONSTRAINT ck_defects_duration_positive CHECK (estimated_work_duration_min > 0),
    CONSTRAINT ck_defects_delay_nonnegative CHECK (max_allowed_delay_days >= 0)
);

CREATE INDEX ix_defects_asset_id ON defects (asset_id);
CREATE INDEX ix_defects_department ON defects (department);
CREATE INDEX ix_defects_defect_type ON defects (defect_type);
CREATE INDEX ix_defects_asset_status ON defects (asset_id, status);
CREATE INDEX ix_defects_dept_severity ON defects (department, defect_severity);
CREATE INDEX ix_defects_detected_date ON defects (detected_date);

CREATE TRIGGER trg_defects_updated_at
    BEFORE UPDATE ON defects
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 3. maintenance_tasks
-- Work items needing a possession. Optional link to a defect.
-- ---------------------------------------------------------------------------
CREATE TABLE maintenance_tasks (
    task_id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id                integer        NOT NULL,
    department              varchar(32)   NOT NULL,
    task_type               varchar(80)   NOT NULL,
    linked_defect_id       integer,
    priority_score          double precision NOT NULL DEFAULT 0.0,
    failure_prob_7d        double precision NOT NULL DEFAULT 0.0,
    failure_prob_30d       double precision NOT NULL DEFAULT 0.0,
    urgency_score           double precision NOT NULL DEFAULT 0.0,
    estimated_duration_min integer        NOT NULL,
    earliest_start_date     date           NOT NULL,
    latest_end_date         date           NOT NULL,
    preferred_shift         varchar(16)   NOT NULL DEFAULT 'any',
    status                  varchar(24)   NOT NULL DEFAULT 'pending',
    source_system            varchar(40)   NOT NULL,
    created_at              timestamptz   NOT NULL DEFAULT now(),
    updated_at              timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT fk_tasks_asset
        FOREIGN KEY (asset_id)
        REFERENCES assets (asset_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_tasks_linked_defect
        FOREIGN KEY (linked_defect_id)
        REFERENCES defects (defect_id)
        ON DELETE SET NULL,
    CONSTRAINT ck_tasks_priority_range CHECK (
        priority_score >= 0 AND priority_score <= 100
    ),
    CONSTRAINT ck_tasks_fail_prob_7d CHECK (
        failure_prob_7d >= 0 AND failure_prob_7d <= 1
    ),
    CONSTRAINT ck_tasks_fail_prob_30d CHECK (
        failure_prob_30d >= 0 AND failure_prob_30d <= 1
    ),
    CONSTRAINT ck_tasks_fail_prob_horizon CHECK (failure_prob_30d >= failure_prob_7d),
    CONSTRAINT ck_tasks_urgency_range CHECK (
        urgency_score >= 0 AND urgency_score <= 100
    ),
    CONSTRAINT ck_tasks_duration_positive CHECK (estimated_duration_min > 0),
    CONSTRAINT ck_tasks_date_window CHECK (latest_end_date >= earliest_start_date),
    CONSTRAINT ck_tasks_preferred_shift CHECK (
        preferred_shift IN ('day', 'night', 'any')
    ),
    CONSTRAINT ck_tasks_status CHECK (
        status IN ('pending', 'scored', 'scheduled', 'in_progress', 'completed', 'cancelled')
    )
);

CREATE INDEX ix_tasks_asset_id ON maintenance_tasks (asset_id);
CREATE INDEX ix_tasks_department ON maintenance_tasks (department);
CREATE INDEX ix_tasks_task_type ON maintenance_tasks (task_type);
CREATE INDEX ix_tasks_status ON maintenance_tasks (status);
CREATE INDEX ix_tasks_asset_status ON maintenance_tasks (asset_id, status);
CREATE INDEX ix_tasks_dept_priority ON maintenance_tasks (department, priority_score);
CREATE INDEX ix_tasks_window ON maintenance_tasks (earliest_start_date, latest_end_date);
CREATE INDEX ix_tasks_linked_defect ON maintenance_tasks (linked_defect_id);

CREATE TRIGGER trg_maintenance_tasks_updated_at
    BEFORE UPDATE ON maintenance_tasks
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 4. corridor_windows
-- Permitted block slots on a corridor. Overnight slots may wrap midnight
-- (end_time < start_time), so no start/end time ordering check.
-- ---------------------------------------------------------------------------
CREATE TABLE corridor_windows (
    window_id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corridor_id          varchar(40)   NOT NULL,
    section_code          varchar(32)   NOT NULL,
    km_start             numeric(8, 3)  NOT NULL,
    km_end               numeric(8, 3)  NOT NULL,
    valid_date           date           NOT NULL,
    start_time           time           NOT NULL,
    end_time             time           NOT NULL,
    block_type_allowed    varchar(24)   NOT NULL,
    max_duration_min     integer        NOT NULL,
    train_impact_score    numeric(6, 2)  NOT NULL,
    freight_traffic_level varchar(16)   NOT NULL,
    source               varchar(40)   NOT NULL,
    created_at           timestamptz   NOT NULL DEFAULT now(),
    updated_at           timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT ck_windows_km_range CHECK (km_end >= km_start),
    CONSTRAINT ck_windows_duration_positive CHECK (max_duration_min > 0),
    CONSTRAINT ck_windows_train_impact CHECK (
        train_impact_score >= 0 AND train_impact_score <= 100
    ),
    CONSTRAINT ck_windows_block_type_allowed CHECK (
        block_type_allowed IN ('absolute', 'caution', 'power', 'any')
    ),
    CONSTRAINT ck_windows_freight_level CHECK (
        freight_traffic_level IN ('low', 'medium', 'high', 'very_high')
    )
);

CREATE INDEX ix_windows_corridor_id ON corridor_windows (corridor_id);
CREATE INDEX ix_windows_section_code ON corridor_windows (section_code);
CREATE INDEX ix_windows_corridor_date ON corridor_windows (corridor_id, valid_date);
CREATE INDEX ix_windows_section_km ON corridor_windows (section_code, km_start, km_end);
CREATE INDEX ix_windows_valid_slot ON corridor_windows (valid_date, start_time, end_time);

CREATE TRIGGER trg_corridor_windows_updated_at
    BEFORE UPDATE ON corridor_windows
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 5. blocks
-- Planned possessions produced by the optimizer.
-- ---------------------------------------------------------------------------
CREATE TABLE blocks (
    block_id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corridor_id             varchar(40)    NOT NULL,
    section_code             varchar(32)    NOT NULL,
    km_start                numeric(8, 3)  NOT NULL,
    km_end                  numeric(8, 3)  NOT NULL,
    block_date              date            NOT NULL,
    start_time              time            NOT NULL,
    end_time                time            NOT NULL,
    duration_min            integer         NOT NULL,
    block_type              varchar(24)    NOT NULL,
    departments_involved     varchar(32)[]   NOT NULL,
    status                   varchar(24)    NOT NULL DEFAULT 'planned',
    planned_tasks_count     integer         NOT NULL DEFAULT 0,
    estimated_train_impact   numeric(6, 2)  NOT NULL DEFAULT 0,
    created_by              varchar(80)    NOT NULL,
    created_at              timestamptz    NOT NULL DEFAULT now(),
    updated_at              timestamptz    NOT NULL DEFAULT now(),
    CONSTRAINT ck_blocks_km_range CHECK (km_end >= km_start),
    CONSTRAINT ck_blocks_duration_positive CHECK (duration_min > 0),
    CONSTRAINT ck_blocks_task_count CHECK (planned_tasks_count >= 0),
    CONSTRAINT ck_blocks_train_impact CHECK (
        estimated_train_impact >= 0 AND estimated_train_impact <= 100
    ),
    CONSTRAINT ck_blocks_block_type CHECK (
        block_type IN ('absolute', 'caution', 'power')
    ),
    CONSTRAINT ck_blocks_status CHECK (
        status IN ('draft', 'planned', 'approved', 'in_progress', 'completed', 'cancelled')
    )
);

CREATE INDEX ix_blocks_corridor_id ON blocks (corridor_id);
CREATE INDEX ix_blocks_section_code ON blocks (section_code);
CREATE INDEX ix_blocks_block_date ON blocks (block_date);
CREATE INDEX ix_blocks_status ON blocks (status);
CREATE INDEX ix_blocks_corridor_date ON blocks (corridor_id, block_date);
CREATE INDEX ix_blocks_section_km ON blocks (section_code, km_start, km_end);
CREATE INDEX ix_blocks_status_date ON blocks (status, block_date);

CREATE TRIGGER trg_blocks_updated_at
    BEFORE UPDATE ON blocks
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 6. block_tasks
-- Tasks packed into each block. Cascade-delete with the parent block.
-- ---------------------------------------------------------------------------
CREATE TABLE block_tasks (
    id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_id              integer     NOT NULL,
    task_id               integer     NOT NULL,
    department             varchar(32) NOT NULL,
    planned_duration_min  integer     NOT NULL,
    sequence_order         integer     NOT NULL,
    created_at             timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_block_tasks_block
        FOREIGN KEY (block_id)
        REFERENCES blocks (block_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_block_tasks_task
        FOREIGN KEY (task_id)
        REFERENCES maintenance_tasks (task_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_block_tasks_block_task UNIQUE (block_id, task_id),
    CONSTRAINT uq_block_tasks_sequence UNIQUE (block_id, sequence_order),
    CONSTRAINT ck_block_tasks_duration_positive CHECK (planned_duration_min > 0),
    CONSTRAINT ck_block_tasks_sequence_order CHECK (sequence_order >= 1)
);

CREATE INDEX ix_block_tasks_block_id ON block_tasks (block_id);
CREATE INDEX ix_block_tasks_task_id ON block_tasks (task_id);
CREATE INDEX ix_block_tasks_department ON block_tasks (department);

COMMIT;
